---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    rebase-strategy: "auto"

  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "daily"
    rebase-strategy: "auto"
